const data = [
  {
    key: "tradingview.IntervalWidget.intervals",
    value: JSON.stringify(["25", "75", "125", "3M", "6M", "12M"]),
  },
  {
    key: "tradingview.IntervalWidget.quicks",
    value: JSON.stringify([
      "1D",
      "1W",
      "1M",
      "1",
      "3",
      "5",
      "25",
      "15",
      "125",
      "75",
      "3M",
      "6M",
      "12M",
    ]),
  },
  {
    key: "_tv_drawingTemplates",
    value: JSON.stringify({
      LineToolParallelChannel: {
        1: '{"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":1,"hours":false,"hoursFrom":1,"hoursTo":24,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"level1":{"visible":false,"coeff":-0.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level2":{"visible":true,"coeff":0,"lineStyle":1,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level3":{"visible":false,"coeff":0.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level4":{"visible":false,"coeff":0.5,"lineStyle":2,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level5":{"visible":false,"coeff":0.75,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level6":{"visible":true,"coeff":1,"lineStyle":1,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level7":{"visible":false,"coeff":1.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"extendLeft":false,"extendRight":false,"fillBackground":true,"transparency":20,"labelVisible":true,"labelHorzAlign":"left","labelVertAlign":"bottom","labelFontSize":10,"labelBold":true,"labelItalic":false,"version":2,"labelTextColor":"rgba(0, 0, 0, 1)","backgroundColor":"rgba(0, 128, 0, 0.08)","labelText":"1"}',
        5: '{"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":5,"hours":false,"hoursFrom":1,"hoursTo":24,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"level1":{"visible":false,"coeff":-0.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level2":{"visible":true,"coeff":0,"lineStyle":1,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level3":{"visible":false,"coeff":0.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level4":{"visible":false,"coeff":0.5,"lineStyle":2,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level5":{"visible":false,"coeff":0.75,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level6":{"visible":true,"coeff":1,"lineStyle":1,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level7":{"visible":false,"coeff":1.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"extendLeft":false,"extendRight":false,"fillBackground":true,"transparency":20,"labelVisible":true,"labelHorzAlign":"left","labelVertAlign":"bottom","labelFontSize":10,"labelBold":true,"labelItalic":false,"version":2,"labelTextColor":"rgba(0, 0, 0, 1)","backgroundColor":"rgba(0, 128, 0, 0.08)","labelText":"5"}',
        15: '{"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":15,"hours":false,"hoursFrom":1,"hoursTo":24,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"level1":{"visible":false,"coeff":-0.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level2":{"visible":true,"coeff":0,"lineStyle":1,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level3":{"visible":false,"coeff":0.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level4":{"visible":false,"coeff":0.5,"lineStyle":2,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level5":{"visible":false,"coeff":0.75,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level6":{"visible":true,"coeff":1,"lineStyle":1,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level7":{"visible":false,"coeff":1.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"extendLeft":false,"extendRight":false,"fillBackground":true,"transparency":20,"labelVisible":true,"labelHorzAlign":"left","labelVertAlign":"bottom","labelFontSize":10,"labelBold":true,"labelItalic":false,"version":2,"labelTextColor":"rgba(0, 0, 0, 1)","backgroundColor":"rgba(0, 128, 0, 0.08)","labelText":"15"}',
        25: '{"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":25,"hours":false,"hoursFrom":1,"hoursTo":24,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"level1":{"visible":false,"coeff":-0.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level2":{"visible":true,"coeff":0,"lineStyle":1,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level3":{"visible":false,"coeff":0.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level4":{"visible":false,"coeff":0.5,"lineStyle":2,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level5":{"visible":false,"coeff":0.75,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level6":{"visible":true,"coeff":1,"lineStyle":1,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level7":{"visible":false,"coeff":1.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"extendLeft":false,"extendRight":false,"fillBackground":true,"transparency":20,"labelVisible":true,"labelHorzAlign":"left","labelVertAlign":"bottom","labelFontSize":10,"labelBold":true,"labelItalic":false,"version":2,"labelTextColor":"rgba(0, 0, 0, 1)","backgroundColor":"rgba(0, 128, 0, 0.08)","labelText":"25"}',
        75: '{"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":1,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"level1":{"visible":false,"coeff":-0.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level2":{"visible":true,"coeff":0,"lineStyle":1,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level3":{"visible":false,"coeff":0.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level4":{"visible":false,"coeff":0.5,"lineStyle":2,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level5":{"visible":false,"coeff":0.75,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level6":{"visible":true,"coeff":1,"lineStyle":1,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level7":{"visible":false,"coeff":1.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"extendLeft":false,"extendRight":false,"fillBackground":true,"transparency":20,"labelVisible":true,"labelHorzAlign":"left","labelVertAlign":"bottom","labelFontSize":10,"labelBold":true,"labelItalic":false,"version":2,"labelTextColor":"rgba(0, 0, 0, 1)","backgroundColor":"rgba(0, 128, 0, 0.08)","labelText":"75"}',
        125: '{"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":2,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"level1":{"visible":false,"coeff":-0.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level2":{"visible":true,"coeff":0,"lineStyle":1,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level3":{"visible":false,"coeff":0.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level4":{"visible":false,"coeff":0.5,"lineStyle":2,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level5":{"visible":false,"coeff":0.75,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level6":{"visible":true,"coeff":1,"lineStyle":1,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level7":{"visible":false,"coeff":1.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"extendLeft":false,"extendRight":false,"fillBackground":true,"transparency":20,"labelVisible":true,"labelHorzAlign":"left","labelVertAlign":"bottom","labelFontSize":10,"labelBold":true,"labelItalic":false,"version":2,"labelTextColor":"rgba(0, 0, 0, 1)","backgroundColor":"rgba(0, 128, 0, 0.08)","labelText":"125"}',
        Y: '{"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":52,"months":true,"monthsFrom":1,"monthsTo":12,"ranges":false},"level1":{"visible":false,"coeff":-0.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level2":{"visible":true,"coeff":0,"lineStyle":1,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level3":{"visible":false,"coeff":0.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level4":{"visible":false,"coeff":0.5,"lineStyle":2,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level5":{"visible":false,"coeff":0.75,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level6":{"visible":true,"coeff":1,"lineStyle":1,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level7":{"visible":false,"coeff":1.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"extendLeft":false,"extendRight":false,"fillBackground":true,"transparency":20,"labelVisible":true,"labelHorzAlign":"left","labelVertAlign":"bottom","labelFontSize":10,"labelBold":true,"labelItalic":false,"version":2,"labelTextColor":"rgba(0, 0, 0, 1)","backgroundColor":"rgba(0, 128, 0, 0.08)","labelText":"Y"}',
        H: '{"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":52,"months":true,"monthsFrom":1,"monthsTo":6,"ranges":false},"level1":{"visible":false,"coeff":-0.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level2":{"visible":true,"coeff":0,"lineStyle":1,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level3":{"visible":false,"coeff":0.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level4":{"visible":false,"coeff":0.5,"lineStyle":2,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level5":{"visible":false,"coeff":0.75,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level6":{"visible":true,"coeff":1,"lineStyle":1,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level7":{"visible":false,"coeff":1.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"extendLeft":false,"extendRight":false,"fillBackground":true,"transparency":20,"labelVisible":true,"labelHorzAlign":"left","labelVertAlign":"bottom","labelFontSize":10,"labelBold":true,"labelItalic":false,"version":2,"labelTextColor":"rgba(0, 0, 0, 1)","backgroundColor":"rgba(0, 128, 0, 0.08)","labelText":"H"}',
        Q: '{"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":52,"months":true,"monthsFrom":1,"monthsTo":3,"ranges":false},"level1":{"visible":false,"coeff":-0.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level2":{"visible":true,"coeff":0,"lineStyle":1,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level3":{"visible":false,"coeff":0.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level4":{"visible":false,"coeff":0.5,"lineStyle":2,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level5":{"visible":false,"coeff":0.75,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level6":{"visible":true,"coeff":1,"lineStyle":1,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level7":{"visible":false,"coeff":1.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"extendLeft":false,"extendRight":false,"fillBackground":true,"transparency":20,"labelVisible":true,"labelHorzAlign":"left","labelVertAlign":"bottom","labelFontSize":10,"labelBold":true,"labelItalic":false,"version":2,"labelTextColor":"rgba(0, 0, 0, 1)","backgroundColor":"rgba(0, 128, 0, 0.08)","labelText":"Q"}',
        M: '{"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":52,"months":true,"monthsFrom":1,"monthsTo":1,"ranges":false},"level1":{"visible":false,"coeff":-0.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level2":{"visible":true,"coeff":0,"lineStyle":1,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level3":{"visible":false,"coeff":0.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level4":{"visible":false,"coeff":0.5,"lineStyle":2,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level5":{"visible":false,"coeff":0.75,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level6":{"visible":true,"coeff":1,"lineStyle":1,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level7":{"visible":false,"coeff":1.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"extendLeft":false,"extendRight":false,"fillBackground":true,"transparency":20,"labelVisible":true,"labelHorzAlign":"left","labelVertAlign":"bottom","labelFontSize":10,"labelBold":true,"labelItalic":false,"version":2,"labelTextColor":"rgba(0, 0, 0, 1)","backgroundColor":"rgba(0, 128, 0, 0.08)","labelText":"M"}',
        W: '{"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":1,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"level1":{"visible":false,"coeff":-0.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level2":{"visible":true,"coeff":0,"lineStyle":1,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level3":{"visible":false,"coeff":0.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level4":{"visible":false,"coeff":0.5,"lineStyle":2,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level5":{"visible":false,"coeff":0.75,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level6":{"visible":true,"coeff":1,"lineStyle":1,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level7":{"visible":false,"coeff":1.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"extendLeft":false,"extendRight":false,"fillBackground":true,"transparency":20,"labelVisible":true,"labelHorzAlign":"left","labelVertAlign":"bottom","labelFontSize":10,"labelBold":true,"labelItalic":false,"version":2,"labelTextColor":"rgba(0, 0, 0, 1)","backgroundColor":"rgba(0, 128, 0, 0.08)","labelText":"W"}',
        D: '{"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":1,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"level1":{"visible":false,"coeff":-0.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level2":{"visible":true,"coeff":0,"lineStyle":1,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level3":{"visible":false,"coeff":0.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level4":{"visible":false,"coeff":0.5,"lineStyle":2,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level5":{"visible":false,"coeff":0.75,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level6":{"visible":true,"coeff":1,"lineStyle":1,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"level7":{"visible":false,"coeff":1.25,"lineStyle":0,"lineWidth":1,"color":"rgba(0, 0, 0, 1)"},"extendLeft":false,"extendRight":false,"fillBackground":true,"transparency":20,"labelVisible":true,"labelHorzAlign":"left","labelVertAlign":"bottom","labelFontSize":10,"labelBold":true,"labelItalic":false,"version":2,"labelTextColor":"rgba(0, 0, 0, 1)","backgroundColor":"rgba(0, 128, 0, 0.08)","labelText":"D"}',
      },
      LineToolRiskRewardLong: {
        Nk: '{"linecolor":"#808080","linewidth":1,"textcolor":"#ffffff","fontsize":12,"fillLabelBackground":true,"labelBackgroundColor":"#585858","fillBackground":true,"stopBackground":"rgba(242, 54, 69, 0.1)","profitBackground":"rgba(8, 153, 129, 0.1)","stopBackgroundTransparency":80,"profitBackgroundTransparency":80,"drawBorder":false,"borderColor":"#667b8b","compact":false,"riskDisplayMode":"percents","accountSize":1000,"lotSize":1,"risk":25,"alwaysShowStats":false,"showPriceLabels":true,"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":52,"months":true,"monthsFrom":1,"monthsTo":12,"ranges":true},"stopLevel":213,"profitLevel":927}',
      },
      LineToolRectangle: {
        1: '{"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":1,"hours":false,"hoursFrom":1,"hoursTo":24,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"color":"rgba(0, 0, 0, 0.15)","fillBackground":true,"backgroundColor":"rgba(0, 128, 0, 0.08)","linewidth":1,"transparency":50,"showLabel":true,"horzLabelsAlign":"left","vertLabelsAlign":"bottom","textColor":"rgba(0, 0, 0, 1)","fontSize":11,"bold":true,"italic":false,"extendLeft":false,"extendRight":true,"middleLine":{"showLine":false,"lineWidth":1,"lineColor":"#9C27B0","lineStyle":2},"linestyle":0,"text":"1"}',
        5: '{"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":5,"hours":false,"hoursFrom":1,"hoursTo":24,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"color":"rgba(0, 0, 0, 0.15)","fillBackground":true,"backgroundColor":"rgba(0, 128, 0, 0.08)","linewidth":1,"transparency":50,"showLabel":true,"horzLabelsAlign":"left","vertLabelsAlign":"bottom","textColor":"rgba(0, 0, 0, 1)","fontSize":11,"bold":true,"italic":false,"extendLeft":false,"extendRight":true,"middleLine":{"showLine":false,"lineWidth":1,"lineColor":"#9C27B0","lineStyle":2},"linestyle":0,"text":"5"}',
        15: '{"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":15,"hours":false,"hoursFrom":1,"hoursTo":24,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"color":"rgba(0, 0, 0, 0.15)","fillBackground":true,"backgroundColor":"rgba(0, 128, 0, 0.08)","linewidth":1,"transparency":50,"showLabel":true,"horzLabelsAlign":"left","vertLabelsAlign":"bottom","textColor":"rgba(0, 0, 0, 1)","fontSize":11,"bold":true,"italic":false,"extendLeft":false,"extendRight":true,"middleLine":{"showLine":false,"lineWidth":1,"lineColor":"#9C27B0","lineStyle":2},"linestyle":0,"text":"15"}',
        25: '{"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":25,"hours":false,"hoursFrom":1,"hoursTo":24,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"color":"rgba(0, 0, 0, 0.15)","fillBackground":true,"backgroundColor":"rgba(0, 128, 0, 0.08)","linewidth":1,"transparency":50,"showLabel":true,"horzLabelsAlign":"left","vertLabelsAlign":"bottom","textColor":"rgba(0, 0, 0, 1)","fontSize":11,"bold":true,"italic":false,"extendLeft":false,"extendRight":true,"middleLine":{"showLine":false,"lineWidth":1,"lineColor":"#9C27B0","lineStyle":2},"linestyle":0,"text":"25"}',
        75: '{"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":1,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"color":"rgba(0, 0, 0, 0.15)","fillBackground":true,"backgroundColor":"rgba(0, 128, 0, 0.08)","linewidth":1,"transparency":50,"showLabel":true,"horzLabelsAlign":"left","vertLabelsAlign":"bottom","textColor":"rgba(0, 0, 0, 1)","fontSize":11,"bold":true,"italic":false,"extendLeft":false,"extendRight":true,"middleLine":{"showLine":false,"lineWidth":1,"lineColor":"#9C27B0","lineStyle":2},"linestyle":0,"text":"75"}',
        125: '{"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":2,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"color":"rgba(0, 0, 0, 0.15)","fillBackground":true,"backgroundColor":"rgba(0, 128, 0, 0.08)","linewidth":1,"transparency":50,"showLabel":true,"horzLabelsAlign":"left","vertLabelsAlign":"bottom","textColor":"rgba(0, 0, 0, 1)","fontSize":11,"bold":true,"italic":false,"extendLeft":false,"extendRight":true,"middleLine":{"showLine":false,"lineWidth":1,"lineColor":"#9C27B0","lineStyle":2},"linestyle":0,"text":"125"}',
        Y: '{"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":52,"months":true,"monthsFrom":1,"monthsTo":12,"ranges":false},"color":"rgba(0, 0, 0, 0.15)","fillBackground":true,"backgroundColor":"rgba(0, 128, 0, 0.08)","linewidth":1,"transparency":50,"showLabel":true,"horzLabelsAlign":"left","vertLabelsAlign":"bottom","textColor":"rgba(0, 0, 0, 1)","fontSize":11,"bold":true,"italic":false,"extendLeft":false,"extendRight":true,"middleLine":{"showLine":false,"lineWidth":1,"lineColor":"#9C27B0","lineStyle":2},"linestyle":0,"text":"Y"}',
        H: '{"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":52,"months":true,"monthsFrom":1,"monthsTo":6,"ranges":false},"color":"rgba(0, 0, 0, 0.15)","fillBackground":true,"backgroundColor":"rgba(0, 128, 0, 0.08)","linewidth":1,"transparency":50,"showLabel":true,"horzLabelsAlign":"left","vertLabelsAlign":"bottom","textColor":"rgba(0, 0, 0, 1)","fontSize":11,"bold":true,"italic":false,"extendLeft":false,"extendRight":true,"middleLine":{"showLine":false,"lineWidth":1,"lineColor":"#9C27B0","lineStyle":2},"linestyle":0,"text":"H"}',
        Q: '{"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":52,"months":true,"monthsFrom":1,"monthsTo":3,"ranges":false},"color":"rgba(0, 0, 0, 0.15)","fillBackground":true,"backgroundColor":"rgba(0, 128, 0, 0.08)","linewidth":1,"transparency":50,"showLabel":true,"horzLabelsAlign":"left","vertLabelsAlign":"bottom","textColor":"rgba(0, 0, 0, 1)","fontSize":11,"bold":true,"italic":false,"extendLeft":false,"extendRight":true,"middleLine":{"showLine":false,"lineWidth":1,"lineColor":"#9C27B0","lineStyle":2},"linestyle":0,"text":"Q"}',
        M: '{"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":52,"months":true,"monthsFrom":1,"monthsTo":1,"ranges":false},"color":"rgba(0, 0, 0, 0.15)","fillBackground":true,"backgroundColor":"rgba(0, 128, 0, 0.08)","linewidth":1,"transparency":50,"showLabel":true,"horzLabelsAlign":"left","vertLabelsAlign":"bottom","textColor":"rgba(0, 0, 0, 1)","fontSize":11,"bold":true,"italic":false,"extendLeft":false,"extendRight":true,"middleLine":{"showLine":false,"lineWidth":1,"lineColor":"#9C27B0","lineStyle":2},"linestyle":0,"text":"M"}',
        W: '{"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":1,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"color":"rgba(0, 0, 0, 0.15)","fillBackground":true,"backgroundColor":"rgba(0, 128, 0, 0.08)","linewidth":1,"transparency":50,"showLabel":true,"horzLabelsAlign":"left","vertLabelsAlign":"bottom","textColor":"rgba(0, 0, 0, 1)","fontSize":11,"bold":true,"italic":false,"extendLeft":false,"extendRight":true,"middleLine":{"showLine":false,"lineWidth":1,"lineColor":"#9C27B0","lineStyle":2},"linestyle":0,"text":"W"}',
        D: '{"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":1,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"color":"rgba(0, 0, 0, 0.15)","fillBackground":true,"backgroundColor":"rgba(0, 128, 0, 0.08)","linewidth":1,"transparency":50,"showLabel":true,"horzLabelsAlign":"left","vertLabelsAlign":"bottom","textColor":"rgba(0, 0, 0, 1)","fontSize":11,"bold":true,"italic":false,"extendLeft":false,"extendRight":true,"middleLine":{"showLine":false,"lineWidth":1,"lineColor":"#9C27B0","lineStyle":2},"linestyle":0,"text":"D"}',
      },
      LineToolTrendLine: {
        1: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"extendLeft":false,"extendRight":false,"leftEnd":0,"rightEnd":0,"showLabel":true,"horzLabelsAlign":"center","vertLabelsAlign":"bottom","textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"alwaysShowStats":false,"showMiddlePoint":false,"showPriceLabels":false,"showPriceRange":false,"showPercentPriceRange":false,"showPipsPriceRange":false,"showBarsRange":false,"showDateTimeRange":false,"showDistance":false,"showAngle":false,"statsPosition":2,"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":1,"hours":false,"hoursFrom":1,"hoursTo":24,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"1"}',
        5: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"extendLeft":false,"extendRight":false,"leftEnd":0,"rightEnd":0,"showLabel":true,"horzLabelsAlign":"center","vertLabelsAlign":"bottom","textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"alwaysShowStats":false,"showMiddlePoint":false,"showPriceLabels":false,"showPriceRange":false,"showPercentPriceRange":false,"showPipsPriceRange":false,"showBarsRange":false,"showDateTimeRange":false,"showDistance":false,"showAngle":false,"statsPosition":2,"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":5,"hours":false,"hoursFrom":1,"hoursTo":24,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"5"}',
        15: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"extendLeft":false,"extendRight":false,"leftEnd":0,"rightEnd":0,"showLabel":true,"horzLabelsAlign":"center","vertLabelsAlign":"bottom","textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"alwaysShowStats":false,"showMiddlePoint":false,"showPriceLabels":false,"showPriceRange":false,"showPercentPriceRange":false,"showPipsPriceRange":false,"showBarsRange":false,"showDateTimeRange":false,"showDistance":false,"showAngle":false,"statsPosition":2,"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":15,"hours":false,"hoursFrom":1,"hoursTo":24,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"15"}',
        25: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"extendLeft":false,"extendRight":false,"leftEnd":0,"rightEnd":0,"showLabel":true,"horzLabelsAlign":"center","vertLabelsAlign":"bottom","textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"alwaysShowStats":false,"showMiddlePoint":false,"showPriceLabels":false,"showPriceRange":false,"showPercentPriceRange":false,"showPipsPriceRange":false,"showBarsRange":false,"showDateTimeRange":false,"showDistance":false,"showAngle":false,"statsPosition":2,"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":25,"hours":false,"hoursFrom":1,"hoursTo":24,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"25"}',
        75: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"extendLeft":false,"extendRight":false,"leftEnd":0,"rightEnd":0,"showLabel":true,"horzLabelsAlign":"center","vertLabelsAlign":"bottom","textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"alwaysShowStats":false,"showMiddlePoint":false,"showPriceLabels":false,"showPriceRange":false,"showPercentPriceRange":false,"showPipsPriceRange":false,"showBarsRange":false,"showDateTimeRange":false,"showDistance":false,"showAngle":false,"statsPosition":2,"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":1,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"75"}',
        125: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"extendLeft":false,"extendRight":false,"leftEnd":0,"rightEnd":0,"showLabel":true,"horzLabelsAlign":"center","vertLabelsAlign":"bottom","textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"alwaysShowStats":false,"showMiddlePoint":false,"showPriceLabels":false,"showPriceRange":false,"showPercentPriceRange":false,"showPipsPriceRange":false,"showBarsRange":false,"showDateTimeRange":false,"showDistance":false,"showAngle":false,"statsPosition":2,"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":2,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"125"}',
        Y: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"extendLeft":false,"extendRight":false,"leftEnd":0,"rightEnd":0,"showLabel":true,"horzLabelsAlign":"center","vertLabelsAlign":"bottom","textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"alwaysShowStats":false,"showMiddlePoint":false,"showPriceLabels":false,"showPriceRange":false,"showPercentPriceRange":false,"showPipsPriceRange":false,"showBarsRange":false,"showDateTimeRange":false,"showDistance":false,"showAngle":false,"statsPosition":2,"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":52,"months":true,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"Y"}',
        H: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"extendLeft":false,"extendRight":false,"leftEnd":0,"rightEnd":0,"showLabel":true,"horzLabelsAlign":"center","vertLabelsAlign":"bottom","textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"alwaysShowStats":false,"showMiddlePoint":false,"showPriceLabels":false,"showPriceRange":false,"showPercentPriceRange":false,"showPipsPriceRange":false,"showBarsRange":false,"showDateTimeRange":false,"showDistance":false,"showAngle":false,"statsPosition":2,"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":52,"months":true,"monthsFrom":1,"monthsTo":6,"ranges":false},"text":"H"}',
        Q: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"extendLeft":false,"extendRight":false,"leftEnd":0,"rightEnd":0,"showLabel":true,"horzLabelsAlign":"center","vertLabelsAlign":"bottom","textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"alwaysShowStats":false,"showMiddlePoint":false,"showPriceLabels":false,"showPriceRange":false,"showPercentPriceRange":false,"showPipsPriceRange":false,"showBarsRange":false,"showDateTimeRange":false,"showDistance":false,"showAngle":false,"statsPosition":2,"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":52,"months":true,"monthsFrom":1,"monthsTo":3,"ranges":false},"text":"Q"}',
        M: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"extendLeft":false,"extendRight":false,"leftEnd":0,"rightEnd":0,"showLabel":true,"horzLabelsAlign":"center","vertLabelsAlign":"bottom","textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"alwaysShowStats":false,"showMiddlePoint":false,"showPriceLabels":false,"showPriceRange":false,"showPercentPriceRange":false,"showPipsPriceRange":false,"showBarsRange":false,"showDateTimeRange":false,"showDistance":false,"showAngle":false,"statsPosition":2,"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":52,"months":true,"monthsFrom":1,"monthsTo":1,"ranges":false},"text":"M"}',
        W: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"extendLeft":false,"extendRight":false,"leftEnd":0,"rightEnd":0,"showLabel":true,"horzLabelsAlign":"center","vertLabelsAlign":"bottom","textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"alwaysShowStats":false,"showMiddlePoint":false,"showPriceLabels":false,"showPriceRange":false,"showPercentPriceRange":false,"showPipsPriceRange":false,"showBarsRange":false,"showDateTimeRange":false,"showDistance":false,"showAngle":false,"statsPosition":2,"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":1,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"W"}',
        D: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"extendLeft":false,"extendRight":false,"leftEnd":0,"rightEnd":0,"showLabel":true,"horzLabelsAlign":"center","vertLabelsAlign":"bottom","textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"alwaysShowStats":false,"showMiddlePoint":false,"showPriceLabels":false,"showPriceRange":false,"showPercentPriceRange":false,"showPipsPriceRange":false,"showBarsRange":false,"showDateTimeRange":false,"showDistance":false,"showAngle":false,"statsPosition":2,"intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":1,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"D"}',
      },
      LineToolHorzLine: {
        1: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"showPrice":true,"showLabel":true,"textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"horzLabelsAlign":"right","vertLabelsAlign":"middle","intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":1,"hours":false,"hoursFrom":1,"hoursTo":24,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"1"}',
        5: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"showPrice":true,"showLabel":true,"textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"horzLabelsAlign":"right","vertLabelsAlign":"middle","intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":5,"hours":false,"hoursFrom":1,"hoursTo":24,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"5"}',
        15: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"showPrice":true,"showLabel":true,"textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"horzLabelsAlign":"right","vertLabelsAlign":"middle","intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":15,"hours":false,"hoursFrom":1,"hoursTo":24,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"15"}',
        25: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"showPrice":true,"showLabel":true,"textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"horzLabelsAlign":"right","vertLabelsAlign":"middle","intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":25,"hours":false,"hoursFrom":1,"hoursTo":24,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"25"}',
        75: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"showPrice":true,"showLabel":true,"textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"horzLabelsAlign":"right","vertLabelsAlign":"middle","intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":1,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"75"}',
        125: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"showPrice":true,"showLabel":true,"textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"horzLabelsAlign":"right","vertLabelsAlign":"middle","intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":2,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"125"}',
        Y: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"showPrice":true,"showLabel":true,"textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"horzLabelsAlign":"right","vertLabelsAlign":"middle","intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":52,"months":true,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"Y"}',
        H: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"showPrice":true,"showLabel":true,"textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"horzLabelsAlign":"right","vertLabelsAlign":"middle","intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":52,"months":true,"monthsFrom":1,"monthsTo":6,"ranges":false},"text":"H"}',
        Q: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"showPrice":true,"showLabel":true,"textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"horzLabelsAlign":"right","vertLabelsAlign":"middle","intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":52,"months":true,"monthsFrom":1,"monthsTo":3,"ranges":false},"text":"Q"}',
        M: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"showPrice":true,"showLabel":true,"textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"horzLabelsAlign":"right","vertLabelsAlign":"middle","intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":52,"months":true,"monthsFrom":1,"monthsTo":1,"ranges":false},"text":"M"}',
        W: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"showPrice":true,"showLabel":true,"textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"horzLabelsAlign":"right","vertLabelsAlign":"middle","intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":1,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"W"}',
        D: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"showPrice":true,"showLabel":true,"textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"horzLabelsAlign":"right","vertLabelsAlign":"middle","intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":1,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"D"}',
      },
      LineToolHorzRay: {
        1: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"showPrice":true,"showLabel":true,"textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"horzLabelsAlign":"center","vertLabelsAlign":"middle","intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":1,"hours":false,"hoursFrom":1,"hoursTo":24,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"1"}',
        5: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"showPrice":true,"showLabel":true,"textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"horzLabelsAlign":"center","vertLabelsAlign":"middle","intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":5,"hours":false,"hoursFrom":1,"hoursTo":24,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"5"}',
        15: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"showPrice":true,"showLabel":true,"textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"horzLabelsAlign":"center","vertLabelsAlign":"middle","intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":15,"hours":false,"hoursFrom":1,"hoursTo":24,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"15"}',
        25: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"showPrice":true,"showLabel":true,"textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"horzLabelsAlign":"center","vertLabelsAlign":"middle","intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":25,"hours":false,"hoursFrom":1,"hoursTo":24,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"25"}',
        75: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"showPrice":true,"showLabel":true,"textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"horzLabelsAlign":"center","vertLabelsAlign":"middle","intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":1,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"75"}',
        125: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"showPrice":true,"showLabel":true,"textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"horzLabelsAlign":"center","vertLabelsAlign":"middle","intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":2,"days":false,"daysFrom":1,"daysTo":366,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"125"}',
        Y: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"showPrice":true,"showLabel":true,"textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"horzLabelsAlign":"center","vertLabelsAlign":"middle","intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":52,"months":true,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"Y"}',
        H: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"showPrice":true,"showLabel":true,"textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"horzLabelsAlign":"center","vertLabelsAlign":"middle","intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":52,"months":true,"monthsFrom":1,"monthsTo":6,"ranges":false},"text":"H"}',
        Q: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"showPrice":true,"showLabel":true,"textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"horzLabelsAlign":"center","vertLabelsAlign":"middle","intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":52,"months":true,"monthsFrom":1,"monthsTo":3,"ranges":false},"text":"Q"}',
        M: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"showPrice":true,"showLabel":true,"textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"horzLabelsAlign":"center","vertLabelsAlign":"middle","intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":52,"months":true,"monthsFrom":1,"monthsTo":1,"ranges":false},"text":"M"}',
        W: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"showPrice":true,"showLabel":true,"textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"horzLabelsAlign":"center","vertLabelsAlign":"middle","intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":366,"weeks":true,"weeksFrom":1,"weeksTo":1,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"W"}',
        D: '{"linecolor":"rgba(0, 0, 0, 1)","linewidth":1,"linestyle":0,"showPrice":true,"showLabel":true,"textcolor":"rgba(0, 0, 0, 1)","fontsize":10,"bold":true,"italic":false,"horzLabelsAlign":"center","vertLabelsAlign":"middle","intervalsVisibilities":{"ticks":true,"seconds":true,"secondsFrom":1,"secondsTo":59,"minutes":true,"minutesFrom":1,"minutesTo":59,"hours":true,"hoursFrom":1,"hoursTo":24,"days":true,"daysFrom":1,"daysTo":1,"weeks":false,"weeksFrom":1,"weeksTo":52,"months":false,"monthsFrom":1,"monthsTo":12,"ranges":false},"text":"D"}',
      },
    }),
  },
  {
    key: "tradingview.chart.favoriteDrawings",
    value: JSON.stringify([
      "LineToolParallelChannel",
      "LineToolRiskRewardLong",
      "LineToolHorzLine",
      "LineToolHorzRay",
      "LineToolTrendLine",
      "LineToolBrush",
      "LineToolRectangle",
      "LineToolPriceRange",
      "arrow",
    ]),
  },
  {
    key: "tradingview.linetoolhorzray",
    value: JSON.stringify({
      linecolor: "rgba(0, 0, 0, 1)",
      linewidth: 1,
      linestyle: 0,
      showPrice: true,
      showLabel: false,
      textcolor: "rgba(0, 0, 0, 1)",
      fontsize: 10,
      bold: true,
      italic: false,
      horzLabelsAlign: "right",
      vertLabelsAlign: "middle",
      intervalsVisibilities: {
        ticks: true,
        seconds: true,
        secondsFrom: 1,
        secondsTo: 59,
        minutes: true,
        minutesFrom: 1,
        minutesTo: 59,
        hours: true,
        hoursFrom: 1,
        hoursTo: 24,
        days: true,
        daysFrom: 1,
        daysTo: 366,
        weeks: true,
        weeksFrom: 1,
        weeksTo: 52,
        months: true,
        monthsFrom: 1,
        monthsTo: 12,
        ranges: true,
      },
    }),
  },
  {
    key: "tradingview.linetoolbrush",
    value: JSON.stringify({
      linecolor: "rgba(0, 0, 0, 1)",
      linewidth: 1,
      smooth: 5,
      fillBackground: false,
      backgroundColor: "#00bcd4",
      transparency: 50,
      leftEnd: 0,
      rightEnd: 0,
      intervalsVisibilities: {
        ticks: true,
        seconds: true,
        secondsFrom: 1,
        secondsTo: 59,
        minutes: true,
        minutesFrom: 1,
        minutesTo: 59,
        hours: true,
        hoursFrom: 1,
        hoursTo: 24,
        days: true,
        daysFrom: 1,
        daysTo: 366,
        weeks: true,
        weeksFrom: 1,
        weeksTo: 52,
        months: true,
        monthsFrom: 1,
        monthsTo: 12,
        ranges: true,
      },
    }),
  },
  {
    key: "tradingview.linetooltrendline",
    value: JSON.stringify({
      linecolor: "rgba(0, 0, 0, 1)",
      linewidth: 1,
      linestyle: 0,
      extendLeft: false,
      extendRight: false,
      leftEnd: 0,
      rightEnd: 0,
      showLabel: false,
      horzLabelsAlign: "center",
      vertLabelsAlign: "bottom",
      textcolor: "#2962FF",
      fontsize: 14,
      bold: false,
      italic: false,
      alwaysShowStats: false,
      showMiddlePoint: false,
      showPriceLabels: false,
      showPriceRange: false,
      showPercentPriceRange: false,
      showPipsPriceRange: false,
      showBarsRange: false,
      showDateTimeRange: false,
      showDistance: false,
      showAngle: false,
      statsPosition: 2,
      intervalsVisibilities: {
        ticks: true,
        seconds: true,
        secondsFrom: 1,
        secondsTo: 59,
        minutes: true,
        minutesFrom: 1,
        minutesTo: 59,
        hours: true,
        hoursFrom: 1,
        hoursTo: 24,
        days: true,
        daysFrom: 1,
        daysTo: 366,
        weeks: true,
        weeksFrom: 1,
        weeksTo: 52,
        months: true,
        monthsFrom: 1,
        monthsTo: 12,
        ranges: true,
      },
    }),
  },
  {
    key: "tradingview.linetoolriskrewardlong",
    value: JSON.stringify({
      linecolor: "#808080",
      linewidth: 1,
      textcolor: "#ffffff",
      fontsize: 12,
      fillLabelBackground: true,
      labelBackgroundColor: "#585858",
      fillBackground: true,
      stopBackground: "rgba(242, 54, 69, 0.1)",
      profitBackground: "rgba(8, 153, 129, 0.1)",
      stopBackgroundTransparency: 80,
      profitBackgroundTransparency: 80,
      drawBorder: false,
      borderColor: "#667b8b",
      compact: false,
      riskDisplayMode: "percents",
      accountSize: 1000,
      lotSize: 1,
      risk: 25,
      alwaysShowStats: false,
      showPriceLabels: true,
      intervalsVisibilities: {
        ticks: true,
        seconds: true,
        secondsFrom: 1,
        secondsTo: 59,
        minutes: true,
        minutesFrom: 1,
        minutesTo: 59,
        hours: true,
        hoursFrom: 1,
        hoursTo: 24,
        days: true,
        daysFrom: 1,
        daysTo: 1,
        weeks: false,

        weeksFrom: 1,
        weeksTo: 52,
        months: false,
        monthsFrom: 1,
        monthsTo: 12,
        ranges: false,
      },
    }),
  },
  {
    key: "tradingview.linetoolparallelchannel",
    value: JSON.stringify({
      intervalsVisibilities: {
        daysTo: 1,
        weeks: false,
        months: false,
        ranges: false,
      },
      level2: {
        lineStyle: 1,
        lineWidth: 1,
        color: "rgba(0, 0, 0, 1)",
      },
      level4: {
        visible: false,
        color: "rgba(0, 0, 0, 1)",
      },
      level6: {
        lineStyle: 1,
        lineWidth: 1,
        color: "rgba(0, 0, 0, 1)",
      },
      transparency: 20,
      labelVisible: true,
      labelFontSize: 10,
      labelBold: true,
      version: 2,
      level1: {
        color: "rgba(0, 0, 0, 1)",
      },
      level3: {
        color: "rgba(0, 0, 0, 1)",
      },
      level5: {
        color: "rgba(0, 0, 0, 1)",
      },
      level7: {
        color: "rgba(0, 0, 0, 1)",
      },
      labelTextColor: "rgba(0, 0, 0, 1)",
      backgroundColor: "rgba(0, 128, 0, 0.08)",
    }),
  },
  {
    key: "tradingview.drawings",
    value: JSON.stringify({
      magnet: true,
      magnetMode: 0,
      stayInDrawingMode: false,
      drawOnAllCharts: true,
      drawOnAllChartsMode: 1,
    }),
  },
];

data.forEach((ob) => {
  localStorage.setItem(ob.key, ob.value);
});
